name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --ignore-scripts --if-present -- --ci --reporters=default --errorOnDeprecated

      - name: Build
        run: npm run build

      - name: Verify no uncommitted changes after build
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo '::error::Build generated uncommitted changes. Please commit build artifacts or adjust build.'
            git diff --name-only
            exit 1
          fi

    # Optionally only run build on PRs from forks if necessary secrets are not required
    # strategy: {}
